---
- name: Gather OS facts
  when:
    - ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - os_family

- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Include OS family variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS family tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
