---
- name: Verify
  hosts:
    - linux
  become: true
  tasks:
  - name: Set certificate path variables | Debian-based
    when:
      - ansible_os_family == 'Debian'
    ansible.builtin.set_fact:
      cert_private_key_path: "{{ cert_private_key_path | default('/etc/ssl/private/cert.key') }}"

  - name: Set certificate path variables | Red Hat-based
    when:
      - ansible_os_family == 'RedHat'
    ansible.builtin.set_fact:
      cert_private_key_path: "{{ cert_private_key_path | default('/etc/pki/tls/private/cert.key') }}"

  - name: Set expected variables
    ansible.builtin.set_fact:
      private_key_owner: "{{ cert_private_key_owner | default('root') }}"
      private_key_group: "{{ cert_private_key_group | default('root') }}"
      private_key_mode: "{{ cert_private_key_mode | default('0600') }}"

  - name: Get private key file info
    ansible.builtin.stat:
      path: "{{ cert_private_key_path }}"
    register: _private_key_info

  - name: Get CSR file info
    ansible.builtin.stat:
      path: "{{ cert_csr_path | default('/tmp/cert.csr') }}"
    register: _csr_info

  - name: Assert that private key info is expected
    ansible.builtin.assert:
      that:
        - _private_key_info.stat.pw_name == private_key_owner
        - _private_key_info.stat.gr_name == private_key_group
        - _private_key_info.stat.mode == private_key_mode

  - name: Assert that CSR exists
    ansible.builtin.assert:
      that:
        - _csr_info.stat.exists == expected_csr
